{"name": "test_login_with_invalid_credentials", "status": "passed", "start": 1696537021042, "stop": 1696537022169, "uuid": "2c7d95c4-16e1-4662-b8a8-3ecc7c86b8a2", "historyId": "63d25ff501081fd9ca920ea2a0aa8197", "testCaseId": "63d25ff501081fd9ca920ea2a0aa8197", "fullName": "tests.test_Login.TestLogin#test_login_with_invalid_credentials", "labels": [{"name": "tag", "value": "@pytest.mark.usefixtures('setup_and_teardown', 'log_on_failure')"}, {"name": "parentSuite", "value": "tests"}, {"name": "suite", "value": "test_Login"}, {"name": "subSuite", "value": "TestLogin"}, {"name": "host", "value": "soumya"}, {"name": "thread", "value": "8692-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.test_Login"}]}