{"name": "test_login_with_invalid_credentials", "status": "passed", "start": 1696500913646, "stop": 1696500914687, "uuid": "c51e2ef7-fec1-47b2-9dbd-28b11144970e", "historyId": "63d25ff501081fd9ca920ea2a0aa8197", "testCaseId": "63d25ff501081fd9ca920ea2a0aa8197", "fullName": "tests.test_Login.TestLogin#test_login_with_invalid_credentials", "labels": [{"name": "tag", "value": "@pytest.mark.usefixtures('setup_and_teardown', 'log_on_failure')"}, {"name": "parentSuite", "value": "tests"}, {"name": "suite", "value": "test_Login"}, {"name": "subSuite", "value": "TestLogin"}, {"name": "host", "value": "soumya"}, {"name": "thread", "value": "26140-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.test_Login"}]}